### ISSUE TITLE
[Bug] MSAL Go interactive login not working in Air-Gapped clouds (USNat and USSec)

### ISSUE THREAD

**Issue by himanshutyagi36** [AzureAD/microsoft-authentication-library-for-go#210] opened 2021-05-11 18:18 UTC
MSAL Go version: latest

**Where is the issue?**
* Public client
    * [ ] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [x] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**
We at Ev2 team have a cli client built in Go. We are using msal/go for authentication purposes. Though the  interactive login is working in Public clouds, it is throwing an error in Air-Gapped clouds(USNat/USSec). We are able to get to the login window in the browser, but there is a error returned as follows:

`server didn't send OAuth state`

 It seems to be thrown here: 
https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/internal/local/server.go#L138

**What version of Go are you using (`go version`)?**
1.15.2

**What operating system and processor architecture are you using (`go env`)?**
windows

**Expected behavior**
The expected behavior is that the user is able to authenticate with AAD and get access token.

**Actual behavior**
User is taken to the browser login page, they enter their credentials and are show the message `Authentication complete...`
When they are back to the respective shell, msal/go throws the error: `server didn't send OAuth state`. 
This is happening in air-gapped clouds (USNat, USSec) only.

**Possible solution**
NA

**Additional context / logs / screenshots**
Can't get any screenshots from these environments.

**Comment by abhidnya13** [comment] 2021-05-13 18:38
Have been having offline conversations regarding this and we are trying to take a look at the logs. Seems like the response that is sent from the server does not have a `code` or `state` parameter as confirmed by the high side engineer after looking at the network traces.

Aside, @himanshutyagi36 I don't identify the version of MSAL you are using. You should use the latest MSAL Go version 0.2.0 : https://github.com/AzureAD/microsoft-authentication-library-for-go/releases from here :https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-library-for-go

**Comment by himanshutyagi36** [comment] 2021-05-13 19:14
@abhidnya13 I did update to the latest version, the issue still remains.

**Comment by abhidnya13** [comment] 2021-05-28 17:09
After investigation, this was found to be because of an existing issue when using IE in Jumpboxes, this works fine with Edge.
Resolving this here, as it is not an MSAL issue.

**Closed by abhidnya13** 2021-05-28 17:09 UTC
