### ISSUE TITLE
Consistency track: please provide consistent APIs to disable authority validation and instance discovery

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-go#301] opened 2022-03-25 16:10 UTC
MSAL Go has no API for this now but when it does, this is only to track the work and to be sure it's consistent with MSAL best practice

**Comment by jennyf19** [comment] 2022-05-18 00:07
@xiangyan99 Can you provide some examples of which APIs you are referring to? Thanks.

**Comment by xiangyan99** [comment] 2022-05-18 16:58
FYI. In msal Python, when creating ClientApplication, we can opt out validate_authority to false. https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py#L164.

User can use it when they want to use a private authority.

.net, java, js have similar functionalities but we have not yet added this support for go.

**Comment by henrik-me** [comment] 2022-11-09 06:03
potentially dupe of: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/289

**Comment by chlowell** [comment] 2023-01-30 17:15
Closed by #362, which added a `WithInstanceDiscovery()` option

**Closed by chlowell** 2023-01-30 17:15 UTC
Labels: enhancement, AzureSdk
